services:
  simulation:
    build:
      context: ./src/edge/simulation
      dockerfile: Dockerfile
    networks:
      - forest-fire-network
    environment:
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
      MINIO: True
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: stations
    depends_on:
      - mqtt-broker
      - minio
    restart: unless-stopped
  treatment:
    build:
      context: ./src/edge/treatment
      dockerfile: Dockerfile
    networks:
      - forest-fire-network
    environment:
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
    depends_on:
      - mqtt-broker
    restart: unless-stopped
