[project]
name = "propagation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kafka>=1.3.5",
    "kafka-python-ng>=2.2.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "paho-mqtt>=2.1.0",
    "scipy>=1.16.3",
]
